// Generated by scripts/build-content.mjs from content/site.md. Do not edit.
// Edit content/site.md, then `npm run content` (dev and build run it too).

import type { SiteContent } from './content-types'

export const content: SiteContent = {
  "intro": {
    "lines": [
      "leaving deep space",
      "through the tube (shorter than it looks)",
      "that blue one is earth",
      "down through the clouds, into istanbul"
    ],
    "skip": "skip the ride",
    "replay": "replay the ride"
  },
  "hero": {
    "greeting": "hi, i am kaan.",
    "name": "kaan",
    "location": "istanbul",
    "time": "local time",
    "scroll": "scroll, we are still landing",
    "body": [
      "physics grad turned ai engineer, working on refusal mechanics and safety in llms through interpretability. building SCL, a new way of doing market research."
    ]
  },
  "currently": {
    "label": "currently working on",
    "items": [
      {
        "since": "2025",
        "title": "refusal geometry in llms",
        "desc": "msc thesis at sabanci, on how refusal behavior and safety representations are encoded inside large language models"
      },
      {
        "since": "2024",
        "title": "SCL, synthetic consumer lab",
        "desc": "ai engineer building synthetic consumer systems for behavior simulation and market research workflows",
        "href": "https://synthetic-consumers.com/"
      },
      {
        "since": "2024",
        "title": "soundboost",
        "desc": "ai engineer on an audio mastering platform, a virtual mastering engineer for musicians",
        "href": "https://soundboost.ai/about"
      }
    ]
  },
  "aboutTeaser": {
    "label": "more about me",
    "link": "the longer story",
    "body": [
      "physics first, at boğaziçi. then a detour through padova that did not work out, then sabancı and a startup. days are product, nights are model internals, the two feed each other more than i expected."
    ],
    "facts": [
      {
        "label": "studied",
        "value": "physics, boğaziçi university"
      },
      {
        "label": "now",
        "value": "msc data science, sabancı university"
      },
      {
        "label": "based in",
        "value": "istanbul"
      },
      {
        "label": "online",
        "value": "kaanhho, and khdoex on github"
      }
    ]
  },
  "resumeTeaser": {
    "label": "resume",
    "link": "the full resume",
    "pdf": "download pdf",
    "body": [
      "where i have been so far, most recent first. the pdf is the same thing, in a shape recruiters like."
    ]
  },
  "writingTeaser": {
    "label": "writing",
    "link": "all writing",
    "body": [
      "notes on interpretability, machine learning, and the occasional detour through life. some in english, some in turkish."
    ]
  },
  "contact": {
    "label": "say hi",
    "email": "write me",
    "body": [
      "if you work on interpretability, or on synthetic consumers, or you just liked the view, write me. i read everything, i answer most of it."
    ]
  },
  "about": {
    "story": [
      "i studied physics, and it left me one habit i cannot turn off: asking what is actually happening underneath. most of ai today runs on models nobody can fully open up and read. that is either scary or interesting, i picked interesting.",
      "after physics i tried a computer science master's in padova. it did not work out, and i wrote about why on the blog, in turkish. the short version: i could not feel myself getting better, so i stopped. it was the right call, i still think about it though.",
      "now my thesis at sabanci is on the refusal direction in llms. when a model says \"i can't help with that\", something specific happens inside, and it can be shown as a direction in activation space. i am mapping how jailbreaks move the model off that direction, and what that means for defense (or attack).",
      "at SCL i build an ai based market research engine: synthetic consumers that behave like real ones, which is a strange sentence to write. days are product, nights are model internals. the two feed each other more than i expected, we will see where it goes."
    ],
    "handles": "online i am khdoex on github, and kaanhho most other places (x, huggingface, linkedin). same person, i just could not keep one handle straight. the name is kaan hacıhaliloğlu in turkish, hacihaliloglu when the keyboard does not cooperate."
  },
  "projects": {
    "intro": [
      "mostly the thesis these days: where refusal lives inside llms. the older ml projects moved down to earlier work, they had their time."
    ],
    "items": [
      {
        "title": "refusal geometry in llms",
        "description": "msc thesis at sabanci: how refusal and harmfulness live in the internal geometry of llms. ask a model something harmful and it refuses, that refusal can be shown as a direction in activation space, and jailbreaks work by pushing the model off it. i am mapping what those attacks actually do to the representations, no public repo yet, we will see where it goes.",
        "status": "current",
        "tags": [
          "Mechanistic Interpretability",
          "Refusal Directions",
          "LLM Safety"
        ]
      },
      {
        "title": "Neural Text Summarization: Comparative Analysis of Transformer Architectures",
        "description": "Comparative study of BART and T5 architectures for automated news summarization, including sentiment-aware evaluation and ROUGE-based benchmarking.",
        "status": "earlier",
        "githubUrl": "https://github.com/khdoex/nlp_news_sum",
        "tags": [
          "Transformers",
          "BART",
          "T5",
          "NLTK",
          "Sentiment Analysis",
          "ROUGE Evaluation"
        ]
      },
      {
        "title": "Multi-Label Classification System for Financial Recommendations",
        "description": "Built a multi-label recommendation system for Isbank using one-vs-all XGBoost with feature engineering and ensemble strategies for improved predictive performance.",
        "status": "earlier",
        "githubUrl": "https://github.com/khdoex/Past_ML_codes/blob/main/isb5-gradient-ensemble.ipynb",
        "tags": [
          "XGBoost",
          "Multi-Label Classification",
          "Feature Engineering",
          "Financial Analytics",
          "Kaggle"
        ]
      },
      {
        "title": "Machine Learning Algorithm Implementations",
        "description": "Collection of practical machine learning implementations, including boosting, ensemble techniques, and feature engineering workflows applied to real-world datasets.",
        "status": "earlier",
        "githubUrl": "https://github.com/khdoex/Past_ML_codes",
        "tags": [
          "XGBoost",
          "Ensemble Methods",
          "Feature Engineering",
          "Data Science",
          "Algorithm Implementation"
        ]
      }
    ]
  },
  "writing": {
    "intro": [
      "notes on interpretability, machine learning, and the occasional detour through life."
    ]
  },
  "resume": {
    "pdf": "download pdf",
    "summary": "AI engineer and grad student working on refusal mechanics and safety in llm through interpretability and SCL a new way of doing market research.",
    "experience": [
      {
        "period": "2025 –",
        "title": "AI Engineer",
        "org": "Synthetic Consumer Lab",
        "orgHref": "https://synthetic-consumers.com/",
        "summary": "Engineering lead responsible for the full product stack: backend, frontend, AI systems, and statistical methodology.",
        "detail": [
          "Architected the platform on a Laravel, Python/FastAPI, and Redis stack",
          "Built agentic systems and solutions for market research, synthetic consumer persona systems grounded in real demographic and behavioral data",
          "agnus, the agent of the market research"
        ],
        "scene": "istanbul"
      },
      {
        "period": "2025 –",
        "title": "Teaching Assistant",
        "org": "Sabancı University",
        "orgHref": "https://sabanciuniv.edu/",
        "summary": "Teaching assistant for the Quantum Programming course, guiding students through quantum computing concepts, circuit design, and practical implementations using quantum programming frameworks.",
        "scene": "interpretability"
      },
      {
        "period": "2024 – 2025",
        "title": "AI Engineer / Data Scientist",
        "org": "SoundBoost",
        "orgHref": "https://soundboost.ai/about",
        "summary": "Designed and deployed deep learning models for audio source separation, classification, and acoustic event detection.",
        "detail": [
          "End-to-end AI pipelines with Django backends for model serving and JavaScript for real-time inference",
          "Led development of AI agents for complex audio processing workflows",
          "Created free tools on SoundBoost like Loudness Penalty, LUFS meter, etc."
        ],
        "scene": "istanbul"
      },
      {
        "period": "2023",
        "title": "AI Engineer Intern",
        "org": "Live The World",
        "orgHref": "https://livetheworld.com/",
        "summary": "Engineered content generation pipelines using llms and web scraping.",
        "detail": [
          "Enhanced web scraping capabilities and developed Python solutions for AI-driven applications"
        ],
        "scene": "istanbul"
      },
      {
        "period": "2022 – 2023",
        "title": "Data Analytics & Process Mining Intern",
        "org": "Allianz TR",
        "orgHref": "https://www.allianz.com.tr/",
        "summary": "Automated Excel reporting workflows using Python and SQL. Built dynamic dashboards for operational visibility and optimized business processes using Celonis process mining.",
        "scene": "istanbul"
      },
      {
        "period": "2020 – 2022",
        "title": "Research Assistant",
        "org": "Boğaziçi University",
        "href": "https://arxiv.org/abs/2407.18402",
        "orgHref": "https://boun.edu.tr/",
        "summary": "Worked on feature engineering and transformer-based architectures for seismic data analysis and earthquake detection.",
        "detail": [
          "Contributed to published research (arXiv:2407.18402)"
        ],
        "scene": "physics"
      },
      {
        "period": "2021 – 2022",
        "title": "Teaching Assistant",
        "org": "Boğaziçi University",
        "orgHref": "https://boun.edu.tr/",
        "summary": "Led QA sessions for Numerical Methods, teaching practical applications of NumPy, SciPy, and Matplotlib through hands-on problem solving.",
        "scene": "physics"
      }
    ],
    "education": [
      {
        "period": "2025 –",
        "title": "M.Sc. in Data Science",
        "org": "Sabancı University",
        "orgHref": "https://sabanciuniv.edu/",
        "summary": "Thesis research on mechanistic interpretability of large language models, studying how refusal and related concepts are represented geometrically in a model’s internal activations. Coursework in advanced deep learning and statistical analysis.",
        "scene": "interpretability"
      },
      {
        "period": "2023 – 2024",
        "title": "Graduate Studies in Computer Science",
        "org": "University of Padua",
        "orgHref": "https://www.unipd.it/en/",
        "summary": "Completed the first year of the M.Sc. program. Advanced coursework in artificial intelligence and deep learning, building strong theoretical foundations in deep learning architectures and algorithmic problem-solving.",
        "scene": "padova"
      },
      {
        "period": "2018 – 2023",
        "title": "B.Sc. in Physics",
        "org": "Boğaziçi University",
        "orgHref": "https://boun.edu.tr/",
        "summary": "was part of the EarthML research group, Science Club",
        "scene": "physics"
      }
    ],
    "projects": [
      {
        "period": "",
        "title": "TÜBİTAK 2209-A",
        "summary": "Developed a high-precision earthquake detection model through interesting feature engineering methods.",
        "scene": "physics"
      },
      {
        "period": "",
        "title": "Earth-ML",
        "summary": "Enhanced time series classification using advanced modeling techniques for geophysical data.",
        "scene": "physics"
      },
      {
        "period": "",
        "title": "Kaggle ML Challenge",
        "href": "https://github.com/khdoex/Past_ML_codes/blob/main/isb5-gradient-ensemble.ipynb",
        "summary": "8th place in Türkiye İş Bankası ML Challenge 5 through effective feature engineering.",
        "scene": "istanbul"
      },
      {
        "period": "",
        "title": "Datathon AI",
        "summary": "3rd place in computer vision competition.",
        "scene": "istanbul"
      },
      {
        "period": "",
        "title": "NLP News Summarization",
        "href": "https://github.com/khdoex/nlp_news_sum",
        "summary": "Comparative evaluation of BART and T5 architectures for summarization tasks.",
        "scene": "interpretability"
      },
      {
        "period": "",
        "title": "\"Burası\" Art Exhibition",
        "summary": "Merged seismic data with artistic representation, fusing science and art.",
        "scene": "physics"
      }
    ],
    "skills": [
      {
        "label": "programming",
        "items": "Python, SQL, JavaScript, TypeScript"
      },
      {
        "label": "ml / dl",
        "items": "PyTorch, XGBoost, CatBoost"
      },
      {
        "label": "ai / llm",
        "items": "LLM APIs (OpenAI, OpenRouter), LangChain, LangGraph, Transformers"
      },
      {
        "label": "interpretability",
        "items": "TransformerLens, nnsight, activation/ablation analysis"
      },
      {
        "label": "backend",
        "items": "FastAPI, Laravel, Django, Celery, Redis"
      },
      {
        "label": "scientific",
        "items": "NumPy, SciPy, Matplotlib, Pandas"
      },
      {
        "label": "hpc",
        "items": "Slurm, multi-GPU / distributed training"
      },
      {
        "label": "tools",
        "items": "Git, Docker, Linux"
      }
    ],
    "certifications": [
      {
        "period": "",
        "title": "Quantum Computing (Bronze)",
        "org": "QTurkey",
        "summary": ""
      },
      {
        "period": "",
        "title": "Excellence in Audio",
        "org": "Hugging Face",
        "summary": ""
      },
      {
        "period": "",
        "title": "Process Mining",
        "org": "Celonis Academy",
        "summary": ""
      },
      {
        "period": "",
        "title": "Building RAG Agents",
        "org": "NVIDIA DLI",
        "summary": ""
      }
    ],
    "languages": "Turkish (native) · English (fluent)"
  },
  "tr": {
    "name": "kaan hacıhaliloğlu",
    "tagline": "yapay zeka mühendisi · yorumlanabilirlik · istanbul",
    "factsLabel": "kısaca",
    "story": [
      "fizik okudum, bana kapatamadığım bir alışkanlık bıraktı: altta gerçekte ne oluyor diye sormak. bugün yapay zekanın çoğu, kimsenin tam olarak açıp okuyamadığı modellerin üstünde çalışıyor. bu ya korkutucu ya da ilginç, ben ilginç olanı seçtim.",
      "şu an sabancı üniversitesi'nde veri bilimi yüksek lisansı yapıyorum, tezim büyük dil modellerinde (llm) reddetme yönü üzerine. bir model \"bu konuda yardımcı olamam\" dediğinde içeride belirli bir şey oluyor ve bu, aktivasyon uzayında bir yön olarak gösterilebiliyor. jailbreak'lerin modeli bu yönden nasıl uzaklaştırdığını ve bunun savunma (ya da saldırı) için ne anlama geldiğini haritalıyorum.",
      "SCL'de (synthetic consumer lab) yapay zeka mühendisiyim: yapay zeka tabanlı bir pazar araştırması motoru kuruyorum, gerçek tüketiciler gibi davranan sentetik tüketiciler. yazması bile garip bir cümle. backend, frontend, ajanlar, istatistik, hepsi bende. SoundBoost'ta da derin öğrenmeyle çalışan bir ses mastering platformunun yapay zeka tarafındayım.",
      "lisansı boğaziçi'nde fizikte bitirdim, EarthML grubunda transformer modelleriyle deprem tespiti üzerine çalıştık. arada padova'da bilgisayar bilimleri yüksek lisansına başladım, olmadı. neden olmadığını [blogda yazdım](/blog/master)."
    ],
    "facts": [
      {
        "label": "şu an",
        "value": "yapay zeka mühendisi, SCL (synthetic consumer lab) ve SoundBoost"
      },
      {
        "label": "araştırma",
        "value": "mekanistik yorumlanabilirlik, llm güvenliği, reddetme yönü"
      },
      {
        "label": "eğitim",
        "value": "sabancı üniversitesi (veri bilimi yl), boğaziçi üniversitesi (fizik lisans)"
      },
      {
        "label": "araçlar",
        "value": "python, pytorch, transformerlens, nnsight, fastapi, laravel, typescript"
      },
      {
        "label": "diller",
        "value": "türkçe (ana dil), ingilizce"
      },
      {
        "label": "kullanıcı adı",
        "value": "kaanhho (x, hugging face, linkedin), khdoex (github)"
      }
    ],
    "links": {
      "blog": "yazılar",
      "projects": "projeler",
      "resume": "cv",
      "email": "e-posta",
      "english": "english"
    }
  },
  "notFound": {
    "title": "nothing here",
    "body": [
      "this page does not exist, or it did once and does not any more."
    ]
  },
  "world": {
    "captions": {
      "saturn": "saturn, where the physics started",
      "blackHole": "a black hole, bending the light behind it",
      "transformer": "a transformer, read one layer at a time",
      "refusal": "the refusal direction",
      "harmful": "harmful prompts",
      "harmless": "harmless prompts"
    },
    "prompt": [
      "how",
      "do",
      "i",
      "pick",
      "a",
      "lock"
    ],
    "answer": "i can't help with that"
  },
  "navigation": {
    "home": "kaan h.",
    "blog": "blog",
    "projects": "projects",
    "about": "about",
    "resume": "resume"
  },
  "footer": {
    "line": "kaan hacihaliloglu · istanbul"
  }
}
