// Generated by scripts/build-content.mjs from content/site.md. Do not edit.
// Edit content/site.md, then `npm run content` (dev and build run it too).

import type { SiteContent } from './content-types'

export const content: SiteContent = {
  "intro": {
    "lines": [
      "leaving deep space",
      "through the tube (shorter than it looks)",
      "we need to get closer",
      "down through the clouds, to see where i am"
    ],
    "skip": "skip the ride",
    "replay": "replay the ride"
  },
  "hero": {
    "greeting": "welcome to my personal website, i am kaan.",
    "name": "kaan",
    "location": "istanbul",
    "time": "local time",
    "scroll": "keep scrolling",
    "body": [
      "currently i am tech lead at SCL, writing my thesis, and doing research on the interpretability and safety of large language models."
    ]
  },
  "currently": {
    "label": "currently working on",
    "items": [
      {
        "since": "2025",
        "title": "refusal geometry in llms",
        "desc": "msc thesis at sabancı university, on how refusal behavior and safety representations are encoded inside large language models."
      },
      {
        "since": "2024",
        "title": "SCL, synthetic consumer lab",
        "desc": "building synthetic consumer systems for behavior simulation and market research workflows, with a great team.",
        "href": "https://synthetic-consumers.com/"
      },
      {
        "since": "2024",
        "title": "soundboost",
        "desc": "ai engineer on an audio mastering platform, a virtual mastering engineer for musicians. worked on the free tools and the stem splitter, with cool people.",
        "href": "https://soundboost.ai/about"
      }
    ]
  },
  "aboutTeaser": {
    "label": "more about me",
    "link": "the longer story",
    "body": [
      "studied physics at boğaziçi, met machine learning and deep learning in the EarthML research group, and decided to go further into data science and computer science. started a cs master's in padova but that program was not for me, then came data science at sabancı, together with startups. weekdays go to product, nights to the internals of llms."
    ],
    "facts": [
      {
        "label": "studied",
        "value": "physics, boğaziçi university"
      },
      {
        "label": "now",
        "value": "msc data science, sabancı university"
      },
      {
        "label": "based in",
        "value": "istanbul"
      },
      {
        "label": "online",
        "value": "kaanhho, and khdoex on github"
      }
    ]
  },
  "resumeTeaser": {
    "label": "resume",
    "link": "the full resume",
    "pdf": "download pdf",
    "body": [
      "where i have been so far, most recent first. the pdf is the same thing, in a shape recruiters like."
    ]
  },
  "writingTeaser": {
    "label": "writing",
    "link": "all writing",
    "body": [
      "notes on interpretability, machine learning, and the occasional detour through life. some in english, some in turkish. hopefully i will write more soon."
    ]
  },
  "contact": {
    "label": "say hi",
    "email": "tell me anything",
    "body": [
      "if you work on interpretability, or synthetic consumers, or just vibes, write me. i am online most of the time."
    ]
  },
  "about": {
    "story": [
      "studied physics in undergrad, loved the research and the inspiration from my profs at boğaziçi. one of the best decisions i made in my life was studying physics at boun. thanks to Haluk Beker, Alpar Sevgen, Arkadaş Özakın and many more.",
      "while i was studying, Arkadaş hoca taught us machine learning and deep learning in the EarthML research group, where i worked on earthquake detection models and extensive data analysis. i decided to continue down the data science path and did internships at Allianz, and at Live The World, a startup, as an ai engineer.",
      "i started a master's in cs at Padova but didn't quite like the program, or let's say i didn't fit in. after my first year of coursework i didn't want to do any research there, maybe i couldn't meet the right people at that time. i came back to istanbul, to Sabancı for a data science master's, and started working with Dilara Keküllüoğlu. thanks to her i had my research spark again, with refusal dynamics and poisoning attacks on LLMs.",
      "now i am working in a research group on refusal dynamics, and my thesis is on the same topic with more interpretability candies on top. what this means: i look at what's happening while a model refuses a harmful request and try to make sense of the math inside the model. it kind of feels like physics inside an llm architecture, but this is not a definition at all, just me reassuring myself.",
      "i met Berkan Cesur when i came back to istanbul and he taught me a lot about product development. can't lie, amazing person and insane inspiration. in one year with him i got experience in web development, app development, product cycles and a lot more.",
      "then i started at SCL as an ai engineer. with time i took on more responsibility, so i could say i am a bit more than that now. Ömer Ülgen, our ceo, is one of the sharpest people i have worked with, and from Sinan Ülgen i am learning a lot about customer relationships and working B2B."
    ],
    "handles": "online i am khdoex on github, and kaanhho most other places (x, hugging face, linkedin)."
  },
  "projects": {
    "intro": [
      "mostly the thesis these days:"
    ],
    "items": [
      {
        "title": "refusal geometry in llms",
        "description": "msc thesis at sabancı: how refusal and harmfulness live in the internal geometry of llms. ask a model something harmful and it refuses. that refusal can be shown as a direction in activation space, and jailbreaks work by pushing the model off it. i am mapping what those attacks actually do to the representations. no public repo yet, we will see where it goes.",
        "status": "current",
        "tags": [
          "Mechanistic Interpretability",
          "Refusal Directions",
          "LLM Safety"
        ]
      },
      {
        "title": "Neural Text Summarization: Comparative Analysis of Transformer Architectures",
        "description": "Comparative study of BART and T5 for automated news summarization, with sentiment-aware evaluation and ROUGE-based benchmarking.",
        "status": "earlier",
        "githubUrl": "https://github.com/khdoex/nlp_news_sum",
        "tags": [
          "Transformers",
          "BART",
          "T5",
          "NLTK",
          "Sentiment Analysis",
          "ROUGE Evaluation"
        ]
      },
      {
        "title": "Multi-Label Classification System for Financial Recommendations",
        "description": "Multi-label recommendation system for İş Bankası, built with one-vs-all XGBoost, feature engineering, and ensembling.",
        "status": "earlier",
        "githubUrl": "https://github.com/khdoex/Past_ML_codes/blob/main/isb5-gradient-ensemble.ipynb",
        "tags": [
          "XGBoost",
          "Multi-Label Classification",
          "Feature Engineering",
          "Financial Analytics",
          "Kaggle"
        ]
      },
      {
        "title": "Machine Learning Algorithm Implementations",
        "description": "A collection of practical machine learning implementations: boosting, ensemble techniques, and feature engineering workflows on real-world datasets.",
        "status": "earlier",
        "githubUrl": "https://github.com/khdoex/Past_ML_codes",
        "tags": [
          "XGBoost",
          "Ensemble Methods",
          "Feature Engineering",
          "Data Science",
          "Algorithm Implementation"
        ]
      }
    ]
  },
  "writing": {
    "intro": [
      "notes on interpretability, machine learning, and the occasional detour through life."
    ]
  },
  "resume": {
    "pdf": "download pdf",
    "summary": "ai engineer and grad student. i work on refusal and safety in llms through interpretability, and at SCL on a new way of doing market research.",
    "story": {
      "label": "the story so far",
      "chapters": [
        {
          "title": "boğaziçi",
          "period": "2018 – 2023",
          "scene": "bogazici",
          "body": [
            "physics, on a hill over the bosphorus. loved the research and the inspiration from my profs, one of the best decisions i made in my life. in the EarthML research group Arkadaş hoca taught us machine learning and deep learning, and i worked on earthquake detection models and extensive data analysis. i also taught numerical methods, and once we even turned seismic data into an art exhibition. then i continued down the data science path, with internships at Allianz and Live The World."
          ]
        },
        {
          "title": "the habit",
          "scene": "physics",
          "body": [
            "physics left me one habit: when something works, i want to know what is actually happening inside it. first it was physics, then earthquakes, now language models. same question."
          ]
        },
        {
          "title": "padova",
          "period": "2023 – 2024",
          "scene": "padova",
          "body": [
            "a computer science master's in padova. i didn't quite like the program, or let's say i didn't fit in. after the first year of coursework i didn't want to do any research there, maybe i couldn't meet the right people at that time. the long version is on the blog, in turkish."
          ]
        },
        {
          "title": "sabancı",
          "period": "2025 –",
          "scene": "interpretability",
          "body": [
            "back in istanbul, a data science msc at sabancı. working with Dilara Keküllüoğlu, i had my research spark again, with refusal dynamics and poisoning attacks on llms. my thesis is on the same topic with more interpretability candies on top: i look at what's happening while a model refuses a harmful request and try to make sense of the math inside it. i am also a ta for quantum programming on the side.",
            "back in istanbul i also met Berkan Cesur, who taught me a lot about product development. can't lie, amazing person and insane inspiration. in one year with him i got experience in web development, app development, product cycles and a lot more."
          ]
        },
        {
          "title": "now",
          "period": "2025 –",
          "scene": "levent",
          "body": [
            "days are SCL. i started as an ai engineer, and with time i took on more responsibility, so i could say i am a bit more than that now. Ömer Ülgen, our ceo, is one of the sharpest people i have worked with, and from Sinan Ülgen i am learning a lot about customer relationships and working B2B. nights are still the thesis."
          ]
        }
      ]
    },
    "experience": [
      {
        "period": "2025 –",
        "title": "AI Engineer",
        "org": "Synthetic Consumer Lab",
        "orgHref": "https://synthetic-consumers.com/",
        "summary": "Engineering lead responsible for the full product stack: backend, frontend, AI systems, and statistical methodology.",
        "detail": [
          "Architected the platform on Laravel, Python/FastAPI, and Redis",
          "Built agentic systems for market research, and synthetic consumer personas grounded in real demographic and behavioral data",
          "Built agnus, an AI agent for market research"
        ]
      },
      {
        "period": "2025 – 2026",
        "title": "Teaching Assistant",
        "org": "Sabancı University",
        "orgHref": "https://sabanciuniv.edu/",
        "summary": "Teaching assistant for Quantum Programming, guiding students through quantum computing concepts, circuit design, and hands-on implementation with quantum programming frameworks."
      },
      {
        "period": "2024 – 2025",
        "title": "AI Engineer / Data Scientist",
        "org": "SoundBoost",
        "orgHref": "https://soundboost.ai/about",
        "summary": "Designed and deployed deep learning models for audio source separation, classification, and acoustic event detection.",
        "detail": [
          "Built end-to-end AI pipelines, with Django backends for model serving and JavaScript for real-time inference",
          "Led development of AI agents for complex audio processing workflows",
          "Built SoundBoost's free tools, including Loudness Penalty and a LUFS meter"
        ]
      },
      {
        "period": "2023",
        "title": "AI Engineer Intern",
        "org": "Live The World",
        "orgHref": "https://livetheworld.com/",
        "summary": "Built content generation pipelines using LLMs and web scraping.",
        "detail": [
          "Improved the web scraping stack and developed Python tools for AI-driven applications"
        ]
      },
      {
        "period": "2022 – 2023",
        "title": "Data Analytics & Process Mining Intern",
        "org": "Allianz TR",
        "orgHref": "https://www.allianz.com.tr/",
        "summary": "Automated Excel reporting workflows with Python and SQL, built dashboards for operational visibility, and optimized business processes with Celonis process mining."
      },
      {
        "period": "2020 – 2022",
        "title": "Research Assistant",
        "org": "Boğaziçi University",
        "href": "https://arxiv.org/abs/2407.18402",
        "orgHref": "https://boun.edu.tr/",
        "summary": "Worked on feature engineering and transformer-based architectures for seismic data analysis and earthquake detection.",
        "detail": [
          "Contributed to the paper arXiv:2407.18402"
        ]
      },
      {
        "period": "2021 – 2022",
        "title": "Teaching Assistant",
        "org": "Boğaziçi University",
        "orgHref": "https://boun.edu.tr/",
        "summary": "Led problem sessions for Numerical Methods, teaching NumPy, SciPy, and Matplotlib through hands-on problem solving."
      }
    ],
    "education": [
      {
        "period": "2025 –",
        "title": "M.Sc. in Data Science",
        "org": "Sabancı University",
        "orgHref": "https://sabanciuniv.edu/",
        "summary": "Thesis on the mechanistic interpretability of large language models: how refusal and related concepts are represented geometrically in a model's internal activations. Coursework in advanced deep learning and statistical analysis."
      },
      {
        "period": "2023 – 2024",
        "title": "Graduate Studies in Computer Science",
        "org": "University of Padua",
        "orgHref": "https://www.unipd.it/en/",
        "summary": "Completed the first year of the M.Sc. program, with coursework in artificial intelligence, deep learning architectures, and algorithmic problem solving."
      },
      {
        "period": "2018 – 2023",
        "title": "B.Sc. in Physics",
        "org": "Boğaziçi University",
        "orgHref": "https://boun.edu.tr/",
        "summary": "Member of the EarthML research group and the Science Club."
      }
    ],
    "projects": [
      {
        "period": "",
        "title": "TÜBİTAK 2209-A",
        "summary": "Developed an earthquake detection model, with most of the work in feature engineering."
      },
      {
        "period": "",
        "title": "Earth-ML",
        "summary": "Time series classification for geophysical data."
      },
      {
        "period": "",
        "title": "Kaggle ML Challenge",
        "href": "https://github.com/khdoex/Past_ML_codes/blob/main/isb5-gradient-ensemble.ipynb",
        "summary": "8th place in the Türkiye İş Bankası ML Challenge 5, mainly through feature engineering."
      },
      {
        "period": "",
        "title": "Datathon AI",
        "summary": "3rd place in a computer vision competition."
      },
      {
        "period": "",
        "title": "NLP News Summarization",
        "href": "https://github.com/khdoex/nlp_news_sum",
        "summary": "Comparative evaluation of BART and T5 for summarization."
      },
      {
        "period": "",
        "title": "\"Burası\" Art Exhibition",
        "summary": "Turned seismic data into artwork for an exhibition."
      }
    ],
    "skills": [
      {
        "label": "programming",
        "items": "Python, SQL, JavaScript, TypeScript"
      },
      {
        "label": "ml / dl",
        "items": "PyTorch, XGBoost, CatBoost"
      },
      {
        "label": "ai / llm",
        "items": "LLM APIs (OpenAI, OpenRouter), LangChain, LangGraph, Transformers"
      },
      {
        "label": "interpretability",
        "items": "TransformerLens, nnsight, activation/ablation analysis"
      },
      {
        "label": "backend",
        "items": "FastAPI, Laravel, Django, Celery, Redis"
      },
      {
        "label": "scientific",
        "items": "NumPy, SciPy, Matplotlib, Pandas"
      },
      {
        "label": "hpc",
        "items": "Slurm, multi-GPU / distributed training"
      },
      {
        "label": "tools",
        "items": "Git, Docker, Linux"
      }
    ],
    "certifications": [
      {
        "period": "",
        "title": "Quantum Computing (Bronze)",
        "org": "QTurkey",
        "summary": ""
      },
      {
        "period": "",
        "title": "Excellence in Audio",
        "org": "Hugging Face",
        "summary": ""
      },
      {
        "period": "",
        "title": "Process Mining",
        "org": "Celonis Academy",
        "summary": ""
      },
      {
        "period": "",
        "title": "Building RAG Agents",
        "org": "NVIDIA DLI",
        "summary": ""
      }
    ],
    "languages": "Turkish (native) · English (fluent)"
  },
  "notFound": {
    "title": "nothing here",
    "body": [
      "this page does not exist, or it did once and does not anymore."
    ]
  },
  "world": {
    "captions": {
      "saturn": "saturn, where the physics started",
      "blackHole": "a black hole, bending the light behind it",
      "transformer": "a transformer, read one layer at a time",
      "refusal": "the refusal direction",
      "harmful": "harmful prompts",
      "harmless": "harmless prompts"
    },
    "prompt": [
      "how",
      "do",
      "i",
      "pick",
      "a",
      "lock"
    ],
    "answer": "i can't help with that"
  },
  "navigation": {
    "home": "kaan h.",
    "blog": "blog",
    "projects": "projects",
    "about": "about",
    "resume": "resume"
  },
  "footer": {
    "line": "kaan hacıhaliloğlu · istanbul"
  }
}
