import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

// The Cloudflare Workers runtime has no filesystem: process.cwd() is "/",
// fs.existsSync always returns false and fs.readdirSync throws. Markdown posts
// used to be read from disk on every request, so they 404'd in production while
// working under next dev. This runs at build time, where fs is real, and emits
// the raw files as a module so they get bundled the way the MDX posts already
// are. Parsing still happens in lib/posts.ts; this only moves the read.

const POSTS_DIR = join(process.cwd(), 'posts')
const OUT = join(process.cwd(), 'lib', 'markdown-posts.generated.ts')

const files = readdirSync(POSTS_DIR)
  .filter((name) => name.endsWith('.md') || name.endsWith('.html'))
  .sort()

const entries = files.map((fileName) => ({
  fileName,
  raw: readFileSync(join(POSTS_DIR, fileName), 'utf8'),
  mtime: statSync(join(POSTS_DIR, fileName)).mtime.toISOString(),
}))

const body = `// Generated by scripts/build-posts.mjs. Do not edit.
// Regenerate with \`npm run posts\`; predev and prebuild do it for you.

export interface RawPost {
  fileName: string
  raw: string
  mtime: string
}

export const rawPosts: RawPost[] = ${JSON.stringify(entries, null, 2)}
`

mkdirSync(join(process.cwd(), 'lib'), { recursive: true })
writeFileSync(OUT, body)
console.log(`posts: bundled ${entries.length} file(s) -> lib/markdown-posts.generated.ts`)
